### ISSUE TITLE
Handling words with apostrophes  

### ISSUE THREAD

**Issue by bradydan** [gouch/to-title-case#17]
Words containing apostrophes aren't handled correctly. 

Don'T --> Don'T

Related: converting all caps to title case in Excel has the same limitation

**Comment by gouch** [comment]
That's actually intentional behavior: If a word uses mixed case it's probably a proper noun (like _GitHub_), so the script shouldn't mangle it.

If you want to force it, you can apply `toLowerCase()` to your input first, but [be aware](https://github.com/gouch/to-title-case/issues/1#issuecomment-2785310) that there are lots of legitimate uses of all caps words.

**Comment by bradydan** [comment]
Ok, makes sense. I'm considering using this for product titles so there would it normally be a need for mixed case. The source text (not supplied by me) is all caps, which are converted in Excel to title case, but any contractions end up like the example I gave. Lowercase first is a good approach, thanks.
